FROM ubuntu:22.04 AS workflow

#install package management
RUN apt update && apt install -y software-properties-common \
    dirmngr \
    apt-transport-https \
    lsb-release \
    ca-certificates \
    wget \
    sudo \
    apt-utils \
    dialog 

# set timezone for package installs
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install package requirements
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 871920D1991BC93C \
    && gpg -a --export 871920D1991BC93C | apt-key add - \
    && apt-add-repository -y "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/" \
    && apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable \
    && apt-get update \
    && apt-get install -y \
    r-recommended \
    r-base \
    gdal-bin \
    libgdal-dev \
    curl \
    python-is-python3 \
    python3-pip \
    python3-virtualenv \
    python3-rpy2 \
    python3-cffi \
    build-essential \
    libbz2-dev \
    libudunits2-dev \
    gfortran \
    libmagick++-dev

ENV PROJ_LIB=/usr/share/proj
    
# Install the R dependancies
WORKDIR /app/r-functions/

RUN mkdir -p /app/renv/

# Install renv
RUN R -e "install.packages('renv', repos = c(CRAN = 'https://cloud.r-project.org'))"

# Copy the renv files
COPY app/r-functions/renv/ ./renv/
COPY app/r-functions/.Rprofile .
COPY app/r-functions/renv.lock .

ENV RENV_PATHS_ROOT=/app/renv

# Restore the renv environment
RUN R -e "renv::consent(provided = TRUE); renv::restore(lockfile='/app/r-functions/renv.lock')"

# Install app
WORKDIR /app

# Install workflow dependencies
COPY app/workflow/requirements.txt ./workflow/
RUN pip3 install -r /app/workflow/requirements.txt

# Copy the R functions
COPY app/r-functions/workflow/*.R ./r-functions/workflow/

# Copy the Workflow
COPY app/workflow/ ./workflow

# Bring in the container config
RUN mkdir /etc/luigi/
COPY config/app/workflow/workflow-luigi.cfg /etc/luigi/luigi.cfg

#Initialise startup script and create mount points for Singularity
COPY app/exec.sh ./
RUN chmod +rx /app/exec.sh \
    && mkdir -p /input/ \
    && mkdir -p /state/ \ 
    && mkdir -p /working/ \
    && mkdir -p /output/ 

# Copy any additional build information
COPY config/app/build-info.json /app

EXPOSE 8082

ENTRYPOINT ["/app/exec.sh"]

FROM workflow AS devcontainer

# Complete development environment.

RUN apt update && apt install -y git \
    lsb-release build-essential pkg-config autoconf automake \
    libtool bison flex sed perl parallel libunwind-dev curl vim

# This Dockerfile adds a non-root 'vscode' user with sudo access. However, for Linux,
# this user's GID/UID must match your local user UID/GID to avoid permission issues
# with bind mounts. Update USER_UID / USER_GID if yours is not 1000. See
# https://aka.ms/vscode-remote/containers/non-root-user for details.
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# install base container packages and prep for VSCode
RUN apt-get update \
    # Verify process tools, lsb-release (common in install instructions for CLIs) installed
    && apt-get -y install iproute2 procps lsb-release \
    # Create a non-root user to use if preferred - see https://aka.ms/vscode-remote/containers/non-root-user.
    && groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
    # [Optional] Add sudo support for the non-root user
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Install oh my zsh for vscode user
ADD install-oh-my-zsh.sh /tmp
RUN chmod +x /tmp/install-oh-my-zsh.sh  && \
     sudo -u vscode sh -c /tmp/install-oh-my-zsh.sh && \
     rm /tmp/install-oh-my-zsh.sh

ENTRYPOINT [ "/bin/zsh" ]