import workflow.common.Defaults
import workflow.processing.PrepareProcessing
import workflow.processing.MaskGranule
import workflow.processing.GenerateS1Indices
import workflow.processing.GenerateS2Indices
import workflow.processing.GenerateIndicesCogs
import workflow.processing.CopyIndicesCogsToOutput
import workflow.processing.ValidateIndices
